# -*- coding: utf-8 -*-
"""
Created on Sat Nov 24 10:00:33 2018

@author: MortZ

Project Euler Problem 2
"""

'''
Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed 
four million, find the sum of the even-valued terms.
'''

# !!! Solution keeps a list Fib sequence but requires high memory !!
def sumEvenFib2():
    fib = [1, 2]
    total = 0
    i = 2
    while i <= 4000000:
        if fib[-1] % 2 ==0:
            total += fib[-1]
        fib.append(fib[i-1] + fib[i-2])
        i += 1
    return total


if __name__ == "__main__":
	print(sumEvenFib())
